# coding: utf-8

"""
    Mühle HTTP API

    REST-Schnittstelle für die Mühle-Spielsession. Spiel anlegen, Spieler registrieren, Züge ausführen, Brett und Zustand lesen. Pro Server-Prozess können beliebig viele Partien parallel laufen; jede Partie hat eine eigene `gameId` (UUID), alle Aktionen sind pro Partie isoliert. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.submit_move200_response import SubmitMove200Response

class TestSubmitMove200Response(unittest.TestCase):
    """SubmitMove200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubmitMove200Response:
        """Test SubmitMove200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubmitMove200Response`
        """
        model = SubmitMove200Response()
        if include_optional:
            return SubmitMove200Response(
                message = 'Stone moved'
            )
        else:
            return SubmitMove200Response(
        )
        """

    def testSubmitMove200Response(self):
        """Test SubmitMove200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
