# coding: utf-8

"""
    Mühle HTTP API

    REST-Schnittstelle für die Mühle-Spielsession. Spiel anlegen, Spieler registrieren, Züge ausführen, Brett und Zustand lesen. Pro Server-Prozess können beliebig viele Partien parallel laufen; jede Partie hat eine eigene `gameId` (UUID), alle Aktionen sind pro Partie isoliert. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_add_player(self) -> None:
        """Test case for add_player

        Spieler zum Spiel hinzufügen
        """
        pass

    def test_create_game(self) -> None:
        """Test case for create_game

        Neues Spiel anlegen
        """
        pass

    def test_get_board(self) -> None:
        """Test case for get_board

        Brett mit Feldern
        """
        pass

    def test_get_current_player(self) -> None:
        """Test case for get_current_player

        Farbe des aktuellen Spielers
        """
        pass

    def test_get_game_state(self) -> None:
        """Test case for get_game_state

        Spielphase abfragen
        """
        pass

    def test_get_open_api_spec(self) -> None:
        """Test case for get_open_api_spec

        OpenAPI-Spezifikation (diese Datei)
        """
        pass

    def test_submit_move(self) -> None:
        """Test case for submit_move

        Zug ausführen (setzen, ziehen, entfernen)
        """
        pass


if __name__ == '__main__':
    unittest.main()
