# coding: utf-8

"""
    Mühle HTTP API

    REST-Schnittstelle für die Mühle-Spielsession. Spiel anlegen, Spieler registrieren, Züge ausführen, Brett und Zustand lesen. Pro Server-Prozess können beliebig viele Partien parallel laufen; jede Partie hat eine eigene `gameId` (UUID), alle Aktionen sind pro Partie isoliert. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_board200_response import GetBoard200Response

class TestGetBoard200Response(unittest.TestCase):
    """GetBoard200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetBoard200Response:
        """Test GetBoard200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetBoard200Response`
        """
        model = GetBoard200Response()
        if include_optional:
            return GetBoard200Response(
                board = None
            )
        else:
            return GetBoard200Response(
        )
        """

    def testGetBoard200Response(self):
        """Test GetBoard200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
