# coding: utf-8

# flake8: noqa
"""
    Mühle HTTP API

    REST-Schnittstelle für die Mühle-Spielsession. Spiel anlegen, Spieler registrieren, Züge ausführen, Brett und Zustand lesen. Pro Server-Prozess können beliebig viele Partien parallel laufen; jede Partie hat eine eigene `gameId` (UUID), alle Aktionen sind pro Partie isoliert. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from openapi_client.models.add_player200_response import AddPlayer200Response
from openapi_client.models.create_game201_response import CreateGame201Response
from openapi_client.models.error import Error
from openapi_client.models.get_board200_response import GetBoard200Response
from openapi_client.models.get_current_player200_response import GetCurrentPlayer200Response
from openapi_client.models.get_game_state200_response import GetGameState200Response
from openapi_client.models.submit_move200_response import SubmitMove200Response

