# coding: utf-8

# flake8: noqa

"""
    Mühle HTTP API

    REST-Schnittstelle für die Mühle-Spielsession. Spiel anlegen, Spieler registrieren, Züge ausführen, Brett und Zustand lesen. Pro Server-Prozess können beliebig viele Partien parallel laufen; jede Partie hat eine eigene `gameId` (UUID), alle Aktionen sind pro Partie isoliert. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "DefaultApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AddPlayer200Response",
    "CreateGame201Response",
    "Error",
    "GetBoard200Response",
    "GetCurrentPlayer200Response",
    "GetGameState200Response",
    "SubmitMove200Response",
]

# import apis into sdk package
from openapi_client.api.default_api import DefaultApi as DefaultApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.add_player200_response import AddPlayer200Response as AddPlayer200Response
from openapi_client.models.create_game201_response import CreateGame201Response as CreateGame201Response
from openapi_client.models.error import Error as Error
from openapi_client.models.get_board200_response import GetBoard200Response as GetBoard200Response
from openapi_client.models.get_current_player200_response import GetCurrentPlayer200Response as GetCurrentPlayer200Response
from openapi_client.models.get_game_state200_response import GetGameState200Response as GetGameState200Response
from openapi_client.models.submit_move200_response import SubmitMove200Response as SubmitMove200Response

